### PR TITLE
Compatibility with jquery-ui 1.12.1

### PR DESCRIPTION
**Pull request by theus77**
As jquery-ui is by default loading all plugin this test should be less restricting

### CODE REVIEW

**Comment by joshmaines** [comment]
Is there a reason to make it less picky? I don't see a reason not to check for the specific plugin.

**Comment by theus77** [comment]
I'm using jquery-ui 1.12.1 (the last one I guess) with webpack/yarn. I 'my package dependencies I have this:
`    "jquery-ui": "^1.12.1",
    "nestedSortable": "^1.3.4"
`
and in my js I have this
`
require('jquery-ui');
require('nestedSortable');
`
here is the error I got:
`jquery.mjs.nestedSortable.js:21 Uncaught Error: Cannot find module 'jquery-ui/sortable'`
 I think that they may have moved it to `jquery-ui/ui/widgets/sortable` (and indeed it works when I update the line 21 to this). 

But I'm more a PHP backend developper than a frontend one. So I may be wrong with my webpack config.

**Comment by theus77** [comment]
My bad, I added this `require('jquery-ui/ui/widgets/sortable');` and it works perfectly. Sorry.

**Comment by AJB99** [comment]
@theus77  When you say "I added this `require('jquery-ui/ui/widgets/sortable');` and it works ...", where did you add the require for the sortable widget?

I've run into the same problem myself, but I was already including the sortable plugin in the way that you mentioned worked for you, but it's not working for me.

Here's an illustration:
```
require('jquery')
require('jquery-ui/ui/widgets/draggable')
require('jquery-ui/ui/widgets/droppable')
require('jquery-ui/ui/widgets/resizable')
require('jquery-ui/ui/widgets/sortable')
require('nestedSortable')
```

And the resulting error (from webpack):
```
This dependency was not found:
* jquery-ui/sortable in ./node_modules/nestedSortable/jquery.mjs.nestedSortable.js
To install it, you can run: npm install --save jquery-ui/sortable
```

Thanks in advance for any help.

**Comment by theus77** [comment]
@AJB99, it looks like I finally forked the fille directly in my project, I do not remember why. But it's a good reminder, I should fix that (and remember why I did that. It migth be a good st 

Here the [commit](https://github.com/ems-project/EMSCoreBundle/commit/43eb06944b49cb81f84aac7da78eeb1f54d01a1d#diff-335f95b1b4b240709cc7c341e3da3ab5) in question in my project. And the [js](https://github.com/ems-project/EMSCoreBundle/blob/master/Resources/assets/js/core.js#L47) where those library are imported.

I hope it's help

**Comment by AJB99** [comment]
Hey @theus77,

Thanks for the reply. I ended up forking it myself and then installing it via `npm install ajb99/nestedSortable` so it’s pulling directly from my Github fork repo.


It seems that it was just the package path on line 21 that was the issue. Haven’t run into anything else myself. I’ll post back in here if I do encounter any more bugs.

Cheers!

**Pull request closed without merging**
